Allow GraphQL via ZMQ
mujin/mujinwebstackclientpy pull request #10
Opened 2023-03-24 07:52 UTC by felixvd

As discussed, this allows sending GraphQL queries via ZMQ.

See https://github.com/mujin/controllerclientcpp/pull/124

2023-03-27 03:19 UTC, cielavenir commented on python/mujinwebstackclient/webstackgraphclientutils.py
> +        return self._webstackZmqClient.SendCommand(payload, timeout=timeout)
@felixvd according to test_planningsystem MR output, this SendCommand requires checkpreempt argument

2023-03-27 05:17 UTC, cielavenir requested changes
Working on test_planningsystem revealed that a change like https://github.com/mujin/mujinwebstackclientpy/pull/11/files is required.

If wrong, please show the proper webstack branch.

2023-03-27 05:25 UTC, cielavenir commented on python/mujinwebstackclient/webstackgraphclientutils.py
> +        return self._webstackZmqClient.SendCommand(payload, timeout=timeout)
Please add checkpreempt=True or checkpreempt=False, though it seems just giving warning to stderr...

2023-03-27 05:25 UTC, cielavenir submitted a review, later dismissed
It works

2023-03-27 05:37 UTC, cielavenir commented on python/mujinwebstackclient/webstackgraphclientutils.py
> +        return self._webstackZmqClient.SendCommand(payload, timeout=timeout)['data']
```suggestion
        return self._webstackZmqClient.SendCommand(payload, checkpreempt=False, timeout=timeout)['data']
```

Note: checkpreempt=False is from simulator.mujin.supervisordclient, pretty not sure

2023-03-29 02:43 UTC, cielavenir commented
@felixvd need `SendCommand(sendjson=False)` if payload is msgpack

2023-04-13 01:24 UTC, felixvd commented
We ended up separating the internal client.

2023-04-13 01:24 UTC, closed without merging

2023-04-13 05:48 UTC, cielavenir commented
cf https://github.com/mujin/controllerclientcpp/pull/124#issuecomment-1506272878